[package]
name = "midi-parse-render"
version = "0.1.0"
edition = "2018"
license = "MIT/Apache-2.0"
description = "Utilities for rendering and parsing into/from midi_types::MidiMessage"
authors = ["Mendelt Siebenga <msiebenga@gmail.com>", "Alex Norman <alex@x37v.info>"]
categories = ["no-std", "api-bindings", "multimedia::audio"]
keywords = ["midi"]
readme = "README.md"

[dependencies]

midi-types = { git = "https://github.com/rust-midi/midi-types.git", branch = "main" }

[dev-dependencies]
lazy_static = "1.4.0"
